swagger: '2.0'
info:
  description: An initial attempt to describe the MEC UE Identity API using OpenAPI
  version: 0.0.6
  title: UE Identity API
  termsOfService: TBD
  contact:
    name: TBD
    url: TBD
  license:
    name: ETSI MEC
    url: TBD
externalDocs:
  description: ETSI MEC014 V0.0.6 UE Identity API
  url: 'https://docbox.etsi.org/ISG/MEC/70-Draft/0014UEidentityAPI'
host: '127.0.0.1:8081'
basePath: /uis/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
security:
  - OauthSecurity:
      - all
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: application
    tokenUrl: 'https://oauth.exampleAPI/token'
    scopes:
      all: Single oauth2 scope for API
parameters:
  Body.UeIdentityTagInfo:
    name: ueIdentityTagInfo
    in: body
    description: information of UE identity tag used in UE Identity feature.
    required: true
    schema:
      $ref: '#/definitions/UeIdentityTagInfo'
  Path.AppInstanceId:
    name: appInstanceId
    in: path
    description: Represents a mobile edge application instance
    required: true
    type: string
  Path.UeIdentityTag:
    name: ueIdentityTag
    in: path
    description: Represents a UE
    required: true
    type: string
paths:
  '/{appInstanceId}/ue_identity_tag_info/{ueIdentityTag}':
    get:
      description: retrieves information about a ueIdentityTagInfo resource
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/Path.AppInstanceId'
        - $ref: '#/parameters/Path.UeIdentityTag'
      responses:
        '200':
          description: >-
            It is used to indicate nonspecific success. The response body
            contains a representation of the resource.
          schema:
            required:
              - ueIdentityTagInfo
            properties:
              ueIdentityTagInfo:
                $ref: '#/definitions/UeIdentityTagInfo'
        '400':
          description: >-
            Incorrect parameters were passed in the request.In the returned
            ProblemDetails structure, the "detail" attribute should convey more
            information about the error.
          schema:
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '403':
          description: >-
            The operation is not allowed given the current status of the
            resource. More information should be provided in the "detail"
            attribute of the "ProblemDetails" structure.
          schema:
            required:
              - ProblemDetails
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '404':
          description: >-
            The client provided a URI that cannot be mapped to a valid resource
            URL. In the returned ProblemDetails structure, the "detail"
            attribute should convey more information about the error.
          schema:
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
    put:
      description: 'registers/de-registers a UE identity tag in UE Identity Service '
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/Path.AppInstanceId'
        - $ref: '#/parameters/Path.UeIdentityTag'
        - $ref: '#/parameters/Body.UeIdentityTagInfo'
      responses:
        '200':
          description: >-
            Upon success, a response body containing data type describing the
            updated UeIdentityTagInfo is returned.
          schema:
            required:
              - ueIdentityTagInfo
            properties:
              ueIdentityTagInfo:
                $ref: '#/definitions/UeIdentityTagInfo'
        '400':
          description: >-
            Incorrect parameters were passed in the request.In the returned
            ProblemDetails structure, the "detail" attribute should convey more
            information about the error.
          schema:
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '401':
          description: >-
            An erroneous or missing bearer token. More information should be
            provided in the "detail" attribute of the "ProblemDetails"
            structure.
          schema:
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '403':
          description: >-
            The operation is not allowed given the current status of the
            resource. More information should be provided in the "detail"
            attribute of the "ProblemDetails" structure.
          schema:
            required:
              - ProblemDetails
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '404':
          description: >-
            The client provided a URI that cannot be mapped to a valid resource
            URL. In the returned ProblemDetails structure, the "detail"
            attribute should convey more information about the error.
          schema:
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
        '412':
          description: >-
            It is used when a condition has failed during conditional requests,
            e.g. when using ETags to avoid write conflicts.In the returned
            ProblemDetails structure, the "detail" attribute should convey more
            information about the error.
          schema:
            properties:
              ProblemDetails:
                $ref: '#/definitions/ProblemDetails'
definitions:
  ProblemDetails:
    type: object
    properties:
      type:
        $ref: '#/definitions/Problem.type'
      title:
        $ref: '#/definitions/Problem.title'
      status:
        $ref: '#/definitions/Problem.status'
      detail:
        $ref: '#/definitions/Problem.detail'
      instance:
        $ref: '#/definitions/Problem.instance'
  Problem.type:
    type: string
    format: uri
    description: >-
      A URI reference according to IETF RFC 3986 that identifies the problem
      type
  Problem.title:
    type: string
    description: 'A short, human-readable summary of the problem type'
  Problem.status:
    type: integer
    format: uint32
    description: The HTTP status code for this occurrence of the problem
  Problem.detail:
    type: string
    description: A human-readable explanation specific to this occurrence of the problem
  Problem.instance:
    type: string
    format: uri
    description: A URI reference that identifies the specific occurrence of the problem
  UeIdentityTagInfo:
    description: information of UE identity tag used in UE Identity feature
    type: object
    required:
      - ueIdentityTag
      - state
    properties:
      ueIdentityTag:
        $ref: '#/definitions/UeIdentityTag'
      state:
        $ref: '#/definitions/State'
  UeIdentityTag:
    description: Tag presented by ME Application to ME Platform
    type: string
  State:
    description: status of the resource ueIdentityTagInfo
    type: string
    enum:
      - UNREGISTERED
      - REGISTERED
